# Feature engineering

## 1. Imports

In [1]:
import pandas as pd

## 2. Import data and transform

Leer csv

In [2]:
df = pd.read_csv('../data/clean/train_clean.csv')

In [3]:
df.head()

,Order Date,Ship Date,Ship Mode,Segment,Country,City,State,Region,Category,Sub-Category,Sales
0,2015-01-03,2015-01-07,Standard Class,Consumer,United States,Houston,Texas,Central,Office Supplies,Paper,16.448
1,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Binders,3.540
2,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Storage,272.736
3,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Labels,11.784
4,2015-01-05,2015-01-12,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,East,Office Supplies,Art,19.536

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    9800 non-null   str
 1   Ship Date     9800 non-null   str
 2   Ship Mode     9800 non-null   str
 3   Segment       9800 non-null   str
 4   Country       9800 non-null   str
 5   City          9800 non-null   str
 6   State         9800 non-null   str
 7   Region        9800 non-null   str
 8   Category      9800 non-null   str
 9   Sub-Category  9800 non-null   str
 10  Sales         9800 non-null   float64
dtypes: float64(1), str(10)
memory usage: 842.3 KB

Transformar las fechas.

In [5]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%Y-%m-%d')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%Y-%m-%d')

## 3.

In [6]:
df.head()

,Order Date,Ship Date,Ship Mode,Segment,Country,City,State,Region,Category,Sub-Category,Sales
0,2015-01-03,2015-01-07,Standard Class,Consumer,United States,Houston,Texas,Central,Office Supplies,Paper,16.448
1,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Binders,3.540
2,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Storage,272.736
3,2015-01-04,2015-01-08,Standard Class,Home Office,United States,Naperville,Illinois,Central,Office Supplies,Labels,11.784
4,2015-01-05,2015-01-12,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,East,Office Supplies,Art,19.536