# Modeling

## 1. Imports

In [1]:
import pandas as pd
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

ModuleNotFoundError: No module named 'lightgbm'

## 2. Obtener data

In [2]:
df = pd.read_csv('../data/processed/train_processed.csv')

In [3]:
df.head()

   Order Date     Sales     Lag_1     Lag_2     Lag_3     Lag_4   Rolling_4
0  2015-02-01  2527.914  3092.544  4130.533  4619.108   304.508  3036.67325
1  2015-02-08   968.534  2527.914  3092.544  4130.533  4619.108  3592.52475
2  2015-02-15  2771.054   968.534  2527.914  3092.544  4130.533  2679.88125
3  2015-02-22   224.912  2771.054   968.534  2527.914  3092.544  2340.01150
4  2015-03-01  2289.643   224.912  2771.054   968.534  2527.914  1623.10350

## 3. Separar data

Ahora separaremos la información e intentaremos predecir las 10 últimas semanas.

In [4]:
n_semanas_test = 10

# El "-" para que cuente hacia atrás
train = df.iloc[:-n_semanas_test]

test = df.iloc[-n_semanas_test:]

In [5]:
train.head()

   Order Date     Sales     Lag_1     Lag_2     Lag_3     Lag_4   Rolling_4
0  2015-02-01  2527.914  3092.544  4130.533  4619.108   304.508  3036.67325
1  2015-02-08   968.534  2527.914  3092.544  4130.533  4619.108  3592.52475
2  2015-02-15  2771.054   968.534  2527.914  3092.544  4130.533  2679.88125
3  2015-02-22   224.912  2771.054   968.534  2527.914  3092.544  2340.01150
4  2015-03-01  2289.643   224.912  2771.054   968.534  2527.914  1623.10350

In [6]:
test.head()

,Order Date,Sales,Lag_1,Lag_2,Lag_3,Lag_4,Rolling_4
195,2018-10-28,21535.270,13270.8182,16509.8310,21535.5940,12296.0620,15903.07630
196,2018-11-04,29017.467,21535.2700,13270.8182,16509.8310,21535.5940,18212.87830
197,2018-11-11,20015.550,29017.4670,21535.2700,13270.8182,16509.8310,20083.34655
198,2018-11-18,30572.447,20015.5500,29017.4670,21535.2700,13270.8182,20959.77630
199,2018-11-25,22212.769,30572.4470,20015.5500,29017.4670,21535.2700,25285.18350

Ahora separamos X e y

In [7]:
X_train = train.drop(columns=['Order Date', 'Sales'])
y_train = train['Sales']

X_test = test.drop(columns=['Order Date', 'Sales'])
y_test = test['Sales']

## 4. Modeling

### 4.1 Naive forecast

El naive forecast, hace referencia a simplemente predecir lo que se vendió la semana pasada.

Es la forma más simple de hacer la predicción, no aprende patrones, estacionalidad ni nada. Por lo que cualquier modelo más sofisticado debería de ser mejor que este naive forecast.

Aquí el 'Lag_1' son las ventas de la semana pasada, generaremos una predicción ingenua.

In [ ]:
y_pred_naive = X_test['Lag_1']

naive_mae = mean_absolute_error(y_test, y_pred_naive)
naive_rmse = root_mean_squared_error(y_test, y_pred_naive)

print(f'Naive MAE: {naive_mae:.3f}\nNaive RMSE: {naive_rmse:.3f}')

Naive MAE: 9406.775
Naive MSE: 9830.573

### 4.3 Pruebas con distintos modelos

Modelos a probar

In [ ]:
models = {
    'LinearRegression': LinearRegression(),
    'XGBRegressor': XGBRegressor(),
    'RandomForestRegressor': RandomForestRegressor(),
    'LGBMRegressor': LGBMRegressor()
}

In [ ]:
for name, model in models.items():