# Handle data to SQL

## 1. Imports

In [1]:
import pandas as pd
import os # Para poder buscar las variables de entorno
from dotenv import load_dotenv # Cargar variables de entorno
from sqlalchemy import create_engine

## 2. Import data

In [2]:
df = pd.read_csv('../data/clean/clean_data.csv')
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9784,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429_cardinal_holdit!_binder_insert...,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9785,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,"OFF-AR-10001374_bic_brite_liner_highlighters,_...",Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9786,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977_ge_30524ee4,Technology,Phones,GE 30524EE4,235.188
9787,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912_anker_24w_portable_micro_usb_c...,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9788,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487_sandisk_cruzer_4_gb_usb_flash_...,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9789 entries, 0 to 9788
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9789 non-null   int64
 1   Order ID       9789 non-null   str
 2   Order Date     9789 non-null   str
 3   Ship Date      9789 non-null   str
 4   Ship Mode      9789 non-null   str
 5   Customer ID    9789 non-null   str
 6   Customer Name  9789 non-null   str
 7   Segment        9789 non-null   str
 8   Country        9789 non-null   str
 9   City           9789 non-null   str
 10  State          9789 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9789 non-null   str
 13  Product ID     9789 non-null   str
 14  Category       9789 non-null   str
 15  Sub-Category   9789 non-null   str
 16  Product Name   9789 non-null   str
 17  Sales          9789 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

## 3. Handle data to SQL

### 3.1 Orden inicial

Cambiar 'Order Date' a datetime para ordenar la información

In [4]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')

In [5]:
df = df.sort_values(by='Order Date', ascending=True)

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
7978,7981,CA-2015-103800,2015-01-03,07/01/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095.0,Central,"OFF-PA-10000174_message_book,_wirebound,_four_...",Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448
741,742,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-BI-10004094_gbc_standard_plastic_binding_s...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540
740,741,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-ST-10002743_safco_boltless_steel_shelving,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736
739,740,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-LA-10003223_avery_508,Office Supplies,Labels,Avery 508,11.784
1759,1760,CA-2015-141817,2015-01-05,12/01/2015,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536

Eliminar 'Row ID'y resetear índice.

In [7]:
df = df.drop(columns=['Row ID'])

In [8]:
df.reset_index(inplace=True, drop=True)

In [9]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,CA-2015-103800,2015-01-03,07/01/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095.0,Central,"OFF-PA-10000174_message_book,_wirebound,_four_...",Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448
1,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-BI-10004094_gbc_standard_plastic_binding_s...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540
2,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-ST-10002743_safco_boltless_steel_shelving,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736
3,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-LA-10003223_avery_508,Office Supplies,Labels,Avery 508,11.784
4,CA-2015-141817,2015-01-05,12/01/2015,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536

### 3.2 Get each different product

In [10]:
df_products = df[['Product ID', 'Product Name', 'Category', 'Sub-Category']].drop_duplicates()
df_products.head()

,Product ID,Product Name,Category,Sub-Category
0,"OFF-PA-10000174_message_book,_wirebound,_four_...","Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,Paper
1,OFF-BI-10004094_gbc_standard_plastic_binding_s...,GBC Standard Plastic Binding Systems Combs,Office Supplies,Binders
2,OFF-ST-10002743_safco_boltless_steel_shelving,SAFCO Boltless Steel Shelving,Office Supplies,Storage
3,OFF-LA-10003223_avery_508,Avery 508,Office Supplies,Labels
4,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,Art

Cambiar nombres de las columnas para que coincidan con las de la base de datos.

In [11]:
df_products.columns = [
    'product_id',
    'product_name',
    'category',
    'subcategory'
]
df_products.head()

,product_id,product_name,category,subcategory
0,"OFF-PA-10000174_message_book,_wirebound,_four_...","Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,Paper
1,OFF-BI-10004094_gbc_standard_plastic_binding_s...,GBC Standard Plastic Binding Systems Combs,Office Supplies,Binders
2,OFF-ST-10002743_safco_boltless_steel_shelving,SAFCO Boltless Steel Shelving,Office Supplies,Storage
3,OFF-LA-10003223_avery_508,Avery 508,Office Supplies,Labels
4,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,Art

### 3.3 Get each different geography

In [12]:
df_geography = df[['Country', 'City', 'State', 'Region', 'Postal Code']].drop_duplicates()
df_geography.head()

         Country          City         State   Region  Postal Code
0  United States       Houston         Texas  Central      77095.0
1  United States    Naperville      Illinois  Central      60540.0
4  United States  Philadelphia  Pennsylvania     East      19143.0
5  United States     Henderson      Kentucky    South      42420.0
6  United States        Athens       Georgia    South      30605.0

Cambiar nombres para la base de datos.

In [13]:
df_geography.columns = [
    'country',
    'city',
    'state',
    'region',
    'postal_code'
]
df_geography.head()

         country          city         state   region  postal_code
0  United States       Houston         Texas  Central      77095.0
1  United States    Naperville      Illinois  Central      60540.0
4  United States  Philadelphia  Pennsylvania     East      19143.0
5  United States     Henderson      Kentucky    South      42420.0
6  United States        Athens       Georgia    South      30605.0

Considerar que aquí nos estaría faltando el id de cada geography

### 3.4 Get each different customer

In [14]:
df_customers = df[['Customer ID', 'Customer Name']].drop_duplicates()
df_customers.head()

  Customer ID  Customer Name
0    DP-13000  Darren Powers
1    PO-19195  Phillina Ober
4    MB-18085     Mick Brown
5    ME-17320  Maria Etezadi
6    JO-15145  Jack O'Briant

Cambiar nombres de columnas.

In [15]:
df_customers.columns = ['customer_id', 'customer_name']
df_customers.head()

  customer_id  customer_name
0    DP-13000  Darren Powers
1    PO-19195  Phillina Ober
4    MB-18085     Mick Brown
5    ME-17320  Maria Etezadi
6    JO-15145  Jack O'Briant

### 3.5 Get sales data

Ojo que aquí obtendremos cada registro de venta, luego se va a diferenciar con un id unico.

Además considerar que el geography_id queda pendiente, ya que debemos generarlo primero en la tabla geography.

In [16]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,CA-2015-103800,2015-01-03,07/01/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095.0,Central,"OFF-PA-10000174_message_book,_wirebound,_four_...",Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448
1,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-BI-10004094_gbc_standard_plastic_binding_s...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540
2,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-ST-10002743_safco_boltless_steel_shelving,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736
3,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-LA-10003223_avery_508,Office Supplies,Labels,Avery 508,11.784
4,CA-2015-141817,2015-01-05,12/01/2015,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536

In [17]:
df_sales = df[['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Segment', 'Product ID', 'Customer ID', 'Sales']].drop_duplicates()
df_sales.head()

,Order ID,Order Date,Ship Date,Ship Mode,Segment,Product ID,Customer ID,Sales
0,CA-2015-103800,2015-01-03,07/01/2015,Standard Class,Consumer,"OFF-PA-10000174_message_book,_wirebound,_four_...",DP-13000,16.448
1,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-BI-10004094_gbc_standard_plastic_binding_s...,PO-19195,3.540
2,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-ST-10002743_safco_boltless_steel_shelving,PO-19195,272.736
3,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-LA-10003223_avery_508,PO-19195,11.784
4,CA-2015-141817,2015-01-05,12/01/2015,Standard Class,Consumer,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,MB-18085,19.536

Cambiar nombres de columnas.

In [18]:
df_sales.columns = ['order_id', 'order_date', 'ship_date', 'ship_mode', 'segment', 'product_id', 'customer_id', 'sales']
df_sales.head()

,order_id,order_date,ship_date,ship_mode,segment,product_id,customer_id,sales
0,CA-2015-103800,2015-01-03,07/01/2015,Standard Class,Consumer,"OFF-PA-10000174_message_book,_wirebound,_four_...",DP-13000,16.448
1,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-BI-10004094_gbc_standard_plastic_binding_s...,PO-19195,3.540
2,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-ST-10002743_safco_boltless_steel_shelving,PO-19195,272.736
3,CA-2015-112326,2015-01-04,08/01/2015,Standard Class,Home Office,OFF-LA-10003223_avery_508,PO-19195,11.784
4,CA-2015-141817,2015-01-05,12/01/2015,Standard Class,Consumer,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,MB-18085,19.536

## 4. Connect to database

Para este punto debemos tener una base de datos con las tablas creadas.

Cargar y guardar variables de entorno.

In [19]:
load_dotenv()

True

In [20]:
user = os.getenv('DB_USER')
password = os.getenv('DB_PASSWORD')
host = os.getenv('DB_HOST')
port = os.getenv('DB_PORT')
database = os.getenv('DB_NAME')

Crear engine. Esto sera la conexión a nuestra base de datos.

In [21]:
engine = create_engine(
    f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}'
)

## 5. Load data into database

Productos

In [22]:
df_products.head()

,product_id,product_name,category,subcategory
0,"OFF-PA-10000174_message_book,_wirebound,_four_...","Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,Paper
1,OFF-BI-10004094_gbc_standard_plastic_binding_s...,GBC Standard Plastic Binding Systems Combs,Office Supplies,Binders
2,OFF-ST-10002743_safco_boltless_steel_shelving,SAFCO Boltless Steel Shelving,Office Supplies,Storage
3,OFF-LA-10003223_avery_508,Avery 508,Office Supplies,Labels
4,OFF-AR-10003478_avery_hi-liter_everbold_pen_st...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,Art

In [23]:
df_products.to_sql(
    'product',          # Nombre de la tabla
    engine,             # Conexión a la base de datos
    if_exists='append', # Agregar datos si la tabla ya existe
    index=False         # No añadir como columna el indice del DataFrame
)

892

Geography (ojo que aquí al cargarse, como no se le envió un id)

In [24]:
df_geography.head()

         country          city         state   region  postal_code
0  United States       Houston         Texas  Central      77095.0
1  United States    Naperville      Illinois  Central      60540.0
4  United States  Philadelphia  Pennsylvania     East      19143.0
5  United States     Henderson      Kentucky    South      42420.0
6  United States        Athens       Georgia    South      30605.0

In [25]:
df_geography.to_sql(
    'geography',
    engine,
    if_exists='append',
    index=False
)

627

Customer

In [26]:
df_customers.head()

  customer_id  customer_name
0    DP-13000  Darren Powers
1    PO-19195  Phillina Ober
4    MB-18085     Mick Brown
5    ME-17320  Maria Etezadi
6    JO-15145  Jack O'Briant

In [27]:
df_customers.to_sql(
    'customer',
    engine,
    if_exists='append',
    index=False
)

793